### ISSUE TITLE
Suggestion: add "mlp.wikia.com" valid supported providers.

### ISSUE THREAD

**Issue by j-ok** [DJDavid98/MLPVC-RR#3]
Suggestion: add "mlp.wikia.com" supported providers.
I found these two origins:
1.- vignette(1-9).wikia.nocookie.net/[...]
2.- img(1-9).wikia.nocookie.net/[...]

Sorry I'm not sure the regex (include each possibility or a simpler way).
'((?:[a-z]+([1-9]{1})?\.){0,2})?wikia\.(nocookie\.)?(net|com)\/((?:[a-z0-9\_\/])+)?mlp\/images\/(?:[a-zA-Z0-9\/\_\-\=\.\?\&\%\ñ]+)(\.jpe?g|\.gif|\.png)(?:[a-zA-Z0-9\/\_\-\=\.\?\&\%]+)?'

**Comment by DJDavid98** [comment]
Images from wikia should be uploaded to [sta.sh](http://sta.sh) and linked that way

**Comment by j-ok** [comment]
Ok, thanks. :3
