### ISSUE TITLE
Suggestion: transmit date

### ISSUE THREAD

**Issue by j-ok** [DJDavid98/MLPVC-RR#4]
Suggestion: Add transmit date field in form of "Add an episode" (Useful to control episodes are not transmitted).

Suggestion: Show episode date only in "episode list" table (/episodes), maybe on 'title' html attribute label.

P.D. It is my last idea to for now. I seen a site good operation, I tried to review the code that I can to understand, and not I think of any new feature or issue.

**Comment by DJDavid98** [comment]
From what I can tell, you're using a translator program. I'd prefer if you posted in whatever language you speak, because sentence translations screw up your messages badly. I'll try to translate your messages myself in the future.
